name = "restaurant"
version = "1.0"

# server listen address
addr = "0.0.0.0:2000"

# restaurant config
[restaurant]
openAt = "7:00"
closeAt = "22:00"
table2p = 3
table4p = 2
table6p = 1
table10p = 1
cookNum = 1

[restaurant.menu.gbjd]
name = "宮爆鷄丁"
price = 10.5
stock = 10

[restaurant.menu.yxrs]
name = "鱼香肉丝"
price = 12.0
stock = 2





